

#Deontologisk etik

##Previously
Pratade om konsekvensetik

- Konsekvensetik
  En handlings korrekthet avgörs bara av de konsekvenser som handlingen medför.

Dessa säger att det finns vissa handlingar som är fel i sig, oavsett konsekvens:
- Deontologisk etik
- Pliktetik
  Fokus är att följa plikter än att fokusera på konsekvenser.

# Innehåll

**Maxim** är ett ord för handlingsregel

## Kategoriskt imperativ **II**

Universilitetsprinciper: vad händer i världen genom att tänka "Hur skulle det vara om alla agerade så här?"

"Agera endast efter ett maxim som kan gälla som universalisk lag"

## Två typer av imperativ

Hypotetiskt imperativ: Om du skulle tycka detta, så är denna handling okej.
Men det går inte att följa detta för att det säger att det är moraliskt korekt att tänka så.

##Ljug

Mycket prat om ljug.
Är ljuga alltid fel? Kan aldrig vara säker på de positiva konsekvenserna av lögner.

Autonomi syftar på individers möjlighet till eget val. Är det alltid rätt att låta folk få om de vill? Dödshjälp?

Kantianism: rationalitet, eget val.
Utilitarianism: maximera människors välfärd.
